{% set version = "0.2.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvnfast
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mvnfast_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mvnfast/mvnfast_{{ version }}.tar.gz
  sha256: 8871e0ce54b87afc556fd94ca77c3db72dcbb8c245558287e0fe342e30eec9a0

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bh                         # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-bh
    - r-rcpp >=0.12.0
    - r-rcpparmadillo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.0
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('mvnfast')"           # [not win]
    - "\"%R%\" -e \"library('mvnfast')\""  # [win]

about:
  home: https://github.com/mfasiolo/mvnfast
  license: GPL-2.0-or-later
  summary: "Provides computationally efficient tools related to the multivariate normal and Student's t distributions. The main functionalities are: simulating multivariate random vectors, evaluating multivariate normal or Student's t densities and Mahalanobis distances. These tools are very efficient thanks to the use of\
    \ C++ code and of the OpenMP API."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
