travis:
  secure:
    BINSTAR_TOKEN: I6GUq3CYQIfzPMUc6zMsAAtZ6m+Ep5YaOpFDUz8r5yDTCgoFANaPeRUMHTIeuRpXVRpMCsx27e6bLGGqECsGkzfT60zRFPj5cuuxG18Pkp3UTs3SkMOTAk9XgsWsCUl4dGP6dYi0YtnZ2MxKv0LnsUnz50WkxXq2N2NawW6Caeaor81NZcAlKs1stKFhl8xFviFq4nG/LLAD3yAoocobdLn7yV9zIGewWfwCYr9p7l2ssO0QI8qH3f9GlMkm8Wo4Kki79boJ8+TeSk7rlV6C2dswE75sUulcQP5Smiy6hRHtwv6cqLy2nYoIl7reesSL3ssOFtjFRXhinoctqJCgnojGJoEDYCS4OeVrZkjvBiVVNd6jAiQfezipyeBdx/YEy/jbMVEKjeyoJkmcwFVtjlBObm+PNu7iy3l+j2c1HkXfSvZYvxJDHDx6kGhaQBAe5dcWDaLEDvCpA5sHPUDA3JEtDDZBeaZgY2e+ytewg5M5279IoZQ7C9QZenYbCAOXtn6vm4+H9i5YiuNoCORGYYTvEh5uqCCRNj5PAjRxU5sDLf5k+Fj18C0J8Kazl+pAh9apcTX3uS2jRAweZ8ybWwQSFf+862DHbUH06sDjbXgBsr+LXW1vlUZxZ8cMuiDbE4xPjKT8BYoYNGuM9FPCSDoy5XD0bo5y01QpIKOAXI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
