travis:
  secure:
    BINSTAR_TOKEN: RMppZw8+mx638j29KNKhjFYCC3yJ5WNxbAQOTqDmUgzyoffdlispIkSG8N9FplVmSfj+2hRCtc5bdAnsFV2L8y3K1b1Z6CHKdfVcP3QcDF41AwWbDOP9e7ziSOPJpvvfk3nK95ihZ6I3E4VSyNJD+Lmf8AGpoOYQTL8SrzuKVwQ2WntLR0DKzSHetPxcD16FVpnOZq6z51IEdyiWggB5yFr1G8wdBp3G8c0yGKqGBU+P/E7oVMxKrkII4r5WOgFaTAGw2tQX7pZ2FRM2D3nQiqtdWeAKyoqEM25adTjxGjrIk7d2xGSL7+snOEG04v2OlLdbZnGlq47gwzFyTV2NBYdPO8cISLY9a2Pjx59eiasUW3fjHEWxOyjexrmwd2kSYWY5zRI1u7hAMj/XHYwqR0GOsif+uG7Si/U47Okfgp91bjwmz5E6LBNWoAcE8w7Eg5wIc0wuacP0BbeSAj8fOUpOfW9y+h6zjWKDraCfcCVVXivIeCT0vlgD2w7jEtrTO/J2Hsy3e+WRI3vJeD9abwE5q1w+oAWRZZtkKX02Z9uJwg1px2i2L8nsV1L9InNuRBlQfz8Qf6s5+RCfoiAGaBuY35jcOFpdzyXugoJFQTpj9+RwiA7b0/mxNrs/DXKJmEdJcyVtdTBaPqgcBGQ+Kk6qT8qP62rT6M5NYSMUIck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
